<?php
// SkillShare Hub - Academic Navigation Expanded Data
// 30 fields, 200 courses, 400 subjects (2 per course).
// Returned as an associative array consumed by academic_install.php

return [
    // ============ 30 ACADEMIC FIELDS ============
    'fields' => [
        ['Information Technology', 'fa-laptop-code', '#60a5fa', 'Programming, software development, and modern IT systems'],
        ['Computer Engineering',   'fa-microchip',   '#8b5cf6', 'Computer architecture, hardware, and embedded systems'],
        ['Civil Engineering',      'fa-building',    '#22c55e', 'Design and build infrastructure, structures, and roads'],
        ['Mechanical Engineering', 'fa-gears',       '#f59e0b', 'Machines, manufacturing, thermodynamics, and robotics'],
        ['Electrical Engineering', 'fa-bolt',        '#ef4444', 'Power systems, circuits, and electrical machines'],
        ['Electronics Engineering','fa-microchip',   '#ec4899', 'Electronic circuits, devices, and communication systems'],
        ['Chemical Engineering',   'fa-flask-vial',  '#14b8a6', 'Chemical processes, materials, and industrial production'],
        ['Aerospace Engineering',  'fa-rocket',      '#3b82f6', 'Aircraft, spacecraft, and propulsion systems'],
        ['Medicine & Health Sciences', 'fa-heart-pulse', '#ef4444', 'Medical practice, diagnosis, and patient care'],
        ['Dentistry',              'fa-tooth',       '#f59e0b', 'Oral health, dental surgery, and orthodontics'],
        ['Pharmacy',               'fa-pills',       '#8b5cf6', 'Drug development, pharmacology, and clinical pharmacy'],
        ['Nursing',                'fa-user-nurse',  '#ec4899', 'Patient care, clinical nursing, and health management'],
        ['Biotechnology',          'fa-dna',         '#22c55e', 'Biological systems and bioprocess engineering'],
        ['Agriculture',            'fa-seedling',    '#22c55e', 'Crop science, agronomy, and agricultural management'],
        ['Environmental Science',  'fa-earth-americas', '#14b8a6', 'Ecology, sustainability, and environmental protection'],
        ['Physics',                'fa-atom',        '#3b82f6', 'Matter, energy, and fundamental natural laws'],
        ['Chemistry',              'fa-flask',       '#f59e0b', 'Substances, reactions, and molecular properties'],
        ['Mathematics',            'fa-square-root-variable', '#8b5cf6', 'Numbers, structures, and abstract reasoning'],
        ['Statistics',             'fa-chart-line',  '#60a5fa', 'Data collection, analysis, and interpretation'],
        ['Business Administration','fa-briefcase',   '#ef4444', 'Management, operations, and business strategy'],
        ['Finance & Accounting',   'fa-coins',       '#f59e0b', 'Financial management, accounting, and investment'],
        ['Marketing',              'fa-bullhorn',    '#ec4899', 'Market research, branding, and digital marketing'],
        ['Economics',              'fa-scale-balanced', '#14b8a6', 'Resource allocation and economic systems'],
        ['Law',                    'fa-gavel',       '#3b82f6', 'Legal systems, courts, and justice'],
        ['Education',              'fa-chalkboard-user', '#22c55e', 'Teaching, curriculum, and learning science'],
        ['Psychology',             'fa-brain',       '#8b5cf6', 'Human mind, behavior, and mental health'],
        ['Architecture',           'fa-building-columns', '#f59e0b', 'Building design, spatial planning, and urbanism'],
        ['Arts & Design',          'fa-palette',     '#ec4899', 'Visual arts, creative design, and aesthetics'],
        ['Media & Communication',  'fa-newspaper',   '#60a5fa', 'Journalism, broadcasting, and public relations'],
        ['Hospitality & Tourism',  'fa-umbrella-beach', '#14b8a6', 'Hotels, travel, and tourism management'],
    ],

    // ============ ~200 COURSES grouped by field ============
    // Each course: [name, icon, description]
    'courses' => [
        'Information Technology' => [
            ['BCA', 'fa-graduation-cap', 'Bachelor of Computer Application - programming, web, databases & software'],
            ['BSc CSIT', 'fa-code', 'BSc in Computer Science & Information Technology'],
            ['BIT', 'fa-laptop', 'Bachelor of Information Technology'],
            ['B.Tech Computer Engineering', 'fa-microchip', 'Bachelor of Technology in Computer Engineering'],
            ['Software Engineering', 'fa-cogs', 'Software design, development, testing and project management'],
            ['Computer Science', 'fa-server', 'Core computer science theory and application'],
            ['Information Technology', 'fa-network-wired', 'Applied information technology and systems'],
            ['Data Science', 'fa-database', 'Data analysis, machine learning, and big data'],
        ],
        'Computer Engineering' => [
            ['BE Computer Engineering', 'fa-microchip', 'Bachelor of Engineering in Computer Engineering'],
            ['Computer Engineering', 'fa-cpu', 'Computer hardware, software and networks'],
            ['Embedded Systems', 'fa-robot', 'Embedded programming, microcontrollers and IoT'],
            ['Computer Hardware and Networking', 'fa-sitemap', 'Hardware fundamentals, networking and system admin'],
            ['VLSI Design', 'fa-layer-group', 'Very-large-scale integration and chip design'],
            ['Robotics Engineering', 'fa-robot', 'Robotic systems, automation and control'],
            ['IoT Engineering', 'fa-wifi', 'Internet of Things devices and networks'],
        ],
        'Civil Engineering' => [
            ['BE Civil Engineering', 'fa-building', 'Bachelor of Engineering in Civil Engineering'],
            ['Civil Engineering', 'fa-hard-hat', 'Core civil engineering principles and practice'],
            ['Structural Engineering', 'fa-cubes', 'Design and analysis of structures'],
            ['Transportation Engineering', 'fa-road', 'Highway, traffic and transportation systems'],
            ['Geotechnical Engineering', 'fa-mountain-sun', 'Soil mechanics and foundation engineering'],
            ['Water Resources Engineering', 'fa-water', 'Hydrology, hydraulics and water management'],
            ['Construction Management', 'fa-trowel-bricks', 'Construction planning, scheduling and management'],
        ],
        'Mechanical Engineering' => [
            ['BE Mechanical Engineering', 'fa-gears', 'Bachelor of Engineering in Mechanical Engineering'],
            ['Mechanical Engineering', 'fa-cog', 'Core mechanical systems and design'],
            ['Automobile Engineering', 'fa-car', 'Automotive design, engines and electric vehicles'],
            ['Thermal Engineering', 'fa-fire', 'Thermodynamics, heat transfer and energy systems'],
            ['Manufacturing Engineering', 'fa-industry', 'Production, machining and manufacturing processes'],
            ['Mechatronics', 'fa-robot', 'Integration of mechanical, electronic and software'],
            ['Aerospace Engineering', 'fa-rocket', 'Aircraft and spacecraft design'],
            ['Robotics and Automation', 'fa-robot', 'Industrial robots and automated systems'],
        ],
        'Electrical Engineering' => [
            ['BE Electrical Engineering', 'fa-bolt', 'Bachelor of Engineering in Electrical Engineering'],
            ['Electrical Engineering', 'fa-plug', 'Circuits, machines and power systems'],
            ['Power Systems Engineering', 'fa-tower-broadcast', 'Generation, transmission and distribution'],
            ['Control Systems', 'fa-sliders', 'Automatic control and system dynamics'],
            ['Renewable Energy', 'fa-solar-panel', 'Solar, wind and sustainable energy systems'],
            ['Instrumentation Engineering', 'fa-gauge-high', 'Measurement and control instruments'],
            ['Microelectronics', 'fa-microchip', 'Semiconductor devices and circuits'],
        ],
        'Electronics Engineering' => [
            ['BE Electronics Engineering', 'fa-microchip', 'Bachelor of Engineering in Electronics Engineering'],
            ['Electronics and Communication', 'fa-satellite-dish', 'Electronics, signals and communication systems'],
            ['VLSI and Embedded Systems', 'fa-layer-group', 'Chip design and embedded technology'],
            ['Consumer Electronics', 'fa-tv', 'Design of electronic consumer devices'],
            ['Signal Processing', 'fa-wave-square', 'Digital signal processing and analysis'],
            ['Biomedical Electronics', 'fa-heart-pulse', 'Electronic systems for healthcare'],
            ['Power Electronics', 'fa-plug-circle-bolt', 'Electronic control of power conversion'],
        ],
        'Chemical Engineering' => [
            ['BE Chemical Engineering', 'fa-flask-vial', 'Bachelor of Engineering in Chemical Engineering'],
            ['Chemical Engineering', 'fa-flask', 'Chemical processes and industrial production'],
            ['Petrochemical Engineering', 'fa-oil-well', 'Petroleum and petrochemical processing'],
            ['Polymer Engineering', 'fa-shapes', 'Polymer synthesis and processing'],
            ['Food Technology', 'fa-drumstick-bite', 'Food processing and preservation'],
            ['Pharmaceutical Engineering', 'fa-pills', 'Drug manufacturing and bioprocessing'],
        ],
        'Aerospace Engineering' => [
            ['BE Aerospace Engineering', 'fa-rocket', 'Bachelor of Engineering in Aerospace Engineering'],
            ['Aerospace Engineering', 'fa-plane', 'Aircraft and spacecraft design'],
            ['Avionics', 'fa-plane-up', 'Electronic systems for aircraft'],
            ['Aeronautical Engineering', 'fa-plane', 'Aircraft maintenance and aerodynamics'],
            ['Space Technology', 'fa-satellite', 'Satellites, launch vehicles and space systems'],
            ['Propulsion Systems', 'fa-fire', 'Jet and rocket propulsion engineering'],
        ],
        'Medicine & Health Sciences' => [
            ['MBBS (Doctor of Medicine)', 'fa-user-doctor', 'Bachelor of Medicine and Bachelor of Surgery'],
            ['BDS (Dental Surgery)', 'fa-tooth', 'Bachelor of Dental Surgery'],
            ['BHMS (Homeopathy)', 'fa-leaf', 'Bachelor of Homeopathic Medicine and Surgery'],
            ['BAMS (Ayurveda)', 'fa-mortar-pestle', 'Bachelor of Ayurvedic Medicine and Surgery'],
            ['Physiotherapy', 'fa-person-walking', 'Physical therapy and rehabilitation'],
            ['Public Health', 'fa-people-roof', 'Community health and epidemiology'],
            ['Radiology', 'fa-x-ray', 'Medical imaging and diagnostics'],
            ['Biomedical Science', 'fa-dna', 'Medical research and laboratory science'],
        ],
        'Dentistry' => [
            ['BDS (Dental Surgery)', 'fa-tooth', 'Bachelor of Dental Surgery'],
            ['Orthodontics', 'fa-tooth', 'Braces and teeth alignment'],
            ['Periodontics', 'fa-tooth', 'Gum disease and oral health'],
            ['Prosthodontics', 'fa-tooth', 'Dental prosthetics and implants'],
            ['Oral Surgery', 'fa-tooth', 'Surgical treatment of the mouth and jaw'],
        ],
        'Pharmacy' => [
            ['B.Pharm', 'fa-pills', 'Bachelor of Pharmacy'],
            ['Pharm.D', 'fa-prescription-bottle-medical', 'Doctor of Pharmacy'],
            ['Pharmacology', 'fa-flask', 'Study of drug action and effects'],
            ['Clinical Pharmacy', 'fa-user-doctor', 'Patient-centered pharmaceutical care'],
            ['Pharmaceutical Chemistry', 'fa-atom', 'Chemistry of drug design and synthesis'],
            ['Pharmacognosy', 'fa-leaf', 'Medicinal plants and natural products'],
        ],
        'Nursing' => [
            ['BSc Nursing', 'fa-user-nurse', 'Bachelor of Science in Nursing'],
            ['General Nursing and Midwifery (GNM)', 'fa-user-nurse', 'Diploma in general nursing and midwifery'],
            ['Pediatric Nursing', 'fa-baby', 'Nursing care for children'],
            ['Critical Care Nursing', 'fa-bed-pulse', 'Intensive care and emergency nursing'],
            ['Psychiatric Nursing', 'fa-brain', 'Nursing care for mental health'],
            ['Community Health Nursing', 'fa-people-roof', 'Community-based healthcare'],
        ],
        'Biotechnology' => [
            ['BSc Biotechnology', 'fa-dna', 'Bachelor of Science in Biotechnology'],
            ['Genetic Engineering', 'fa-dna', 'Gene editing and genetic modification'],
            ['Microbiology', 'fa-microscope', 'Study of microorganisms'],
            ['Bioinformatics', 'fa-computer', 'Computational biology and data analysis'],
            ['Immunology', 'fa-shield-virus', 'Immune system and vaccines'],
            ['Industrial Biotechnology', 'fa-industry', 'Biotech applications in industry'],
        ],
        'Agriculture' => [
            ['BSc Agriculture', 'fa-seedling', 'Bachelor of Science in Agriculture'],
            ['Agronomy', 'fa-wheat-awn', 'Crop production and soil management'],
            ['Horticulture', 'fa-tree', 'Fruits, vegetables and ornamental plants'],
            ['Plant Pathology', 'fa-bug', 'Plant diseases and their control'],
            ['Soil Science', 'fa-mound', 'Soil chemistry, fertility and conservation'],
            ['Agricultural Economics', 'fa-chart-line', 'Economics of farming and agribusiness'],
            ['Animal Husbandry', 'fa-cow', 'Livestock production and management'],
        ],
        'Environmental Science' => [
            ['BSc Environmental Science', 'fa-earth-americas', 'Bachelor of Science in Environmental Science'],
            ['Ecology', 'fa-tree', 'Interactions between organisms and environment'],
            ['Environmental Management', 'fa-recycle', 'Sustainable resource and waste management'],
            ['Climate Science', 'fa-sun-cloud', 'Climate change and atmospheric science'],
            ['Water Resource Management', 'fa-water', 'Water conservation and watershed management'],
            ['Environmental Engineering', 'fa-industry', 'Pollution control and environmental systems'],
        ],
        'Physics' => [
            ['BSc Physics', 'fa-atom', 'Bachelor of Science in Physics'],
            ['Theoretical Physics', 'fa-square-root-variable', 'Mathematical models of physical systems'],
            ['Astrophysics', 'fa-star', 'Physics of stars, galaxies and the universe'],
            ['Quantum Physics', 'fa-atom', 'Quantum mechanics and subatomic particles'],
            ['Applied Physics', 'fa-microscope', 'Physics applied to technology'],
            ['Nuclear Physics', 'fa-radiation', 'Atomic nuclei and nuclear energy'],
        ],
        'Chemistry' => [
            ['BSc Chemistry', 'fa-flask', 'Bachelor of Science in Chemistry'],
            ['Organic Chemistry', 'fa-flask', 'Chemistry of carbon compounds'],
            ['Inorganic Chemistry', 'fa-flask', 'Chemistry of metals and inorganic compounds'],
            ['Physical Chemistry', 'fa-flask', 'Physics of chemical systems'],
            ['Analytical Chemistry', 'fa-vial-circle-check', 'Chemical analysis and instrumentation'],
            ['Biochemistry', 'fa-dna', 'Chemistry of living organisms'],
        ],
        'Mathematics' => [
            ['BSc Mathematics', 'fa-square-root-variable', 'Bachelor of Science in Mathematics'],
            ['Pure Mathematics', 'fa-square-root-variable', 'Abstract mathematical structures'],
            ['Applied Mathematics', 'fa-calculator', 'Mathematics applied to real problems'],
            ['Computational Mathematics', 'fa-laptop-code', 'Numerical methods and modeling'],
            ['Mathematical Statistics', 'fa-chart-line', 'Probabilistic and statistical methods'],
            ['Actuarial Science', 'fa-shield-heart', 'Risk assessment and financial modeling'],
        ],
        'Statistics' => [
            ['BSc Statistics', 'fa-chart-line', 'Bachelor of Science in Statistics'],
            ['Data Analytics', 'fa-chart-pie', 'Data analysis and visualization'],
            ['Biostatistics', 'fa-heart-pulse', 'Statistics for health and biology'],
            ['Econometrics', 'fa-chart-line', 'Statistical methods for economics'],
            ['Statistical Computing', 'fa-computer', 'Computational statistics and R/Python'],
        ],
        'Business Administration' => [
            ['BBA', 'fa-briefcase', 'Bachelor of Business Administration'],
            ['MBA', 'fa-briefcase', 'Master of Business Administration'],
            ['Human Resource Management', 'fa-users', 'People management and organizational behavior'],
            ['Operations Management', 'fa-gears', 'Production and supply chain operations'],
            ['Entrepreneurship', 'fa-lightbulb', 'Startup creation and venture management'],
            ['International Business', 'fa-globe', 'Global trade and cross-border business'],
            ['Business Analytics', 'fa-chart-line', 'Data-driven business decision making'],
            ['Project Management', 'fa-diagram-project', 'Planning and managing projects'],
        ],
        'Finance & Accounting' => [
            ['BCom (Commerce)', 'fa-coins', 'Bachelor of Commerce'],
            ['CA (Chartered Accountancy)', 'fa-file-invoice-dollar', 'Professional accounting and auditing'],
            ['Finance', 'fa-coins', 'Financial markets and investment'],
            ['Accounting', 'fa-calculator', 'Financial recording and reporting'],
            ['Investment Banking', 'fa-chart-pie', 'Capital markets and corporate finance'],
            ['Taxation', 'fa-file-invoice', 'Tax law and compliance'],
            ['Auditing', 'fa-magnifying-glass-chart', 'Independent review of financial statements'],
        ],
        'Marketing' => [
            ['BBA Marketing', 'fa-bullhorn', 'Bachelor of Business Administration in Marketing'],
            ['Digital Marketing', 'fa-mobile-screen', 'Online marketing and social media'],
            ['Brand Management', 'fa-tag', 'Brand building and positioning'],
            ['Market Research', 'fa-magnifying-glass', 'Consumer research and insights'],
            ['Advertising', 'fa-tv', 'Creative advertising and campaigns'],
            ['Sales Management', 'fa-handshake', 'Sales strategy and distribution'],
        ],
        'Economics' => [
            ['BA Economics', 'fa-scale-balanced', 'Bachelor of Arts in Economics'],
            ['MA Economics', 'fa-scale-balanced', 'Master of Arts in Economics'],
            ['Development Economics', 'fa-chart-line', 'Economic development and policy'],
            ['Microeconomics', 'fa-scale-balanced', 'Individual economic behavior'],
            ['Macroeconomics', 'fa-building-columns', 'Economy-wide phenomena'],
            ['International Economics', 'fa-globe', 'Global trade and finance'],
        ],
        'Law' => [
            ['LLB', 'fa-gavel', 'Bachelor of Laws'],
            ['LLM', 'fa-gavel', 'Master of Laws'],
            ['Criminal Law', 'fa-handcuffs', 'Crime, defense and prosecution'],
            ['Corporate Law', 'fa-building', 'Business and company law'],
            ['Constitutional Law', 'fa-landmark', 'Constitution and fundamental rights'],
            ['International Law', 'fa-globe', 'Law between nations and international bodies'],
        ],
        'Education' => [
            ['BEd', 'fa-chalkboard-user', 'Bachelor of Education'],
            ['BEd in Primary Education', 'fa-chalkboard', 'Teaching young learners'],
            ['MEd', 'fa-graduation-cap', 'Master of Education'],
            ['Curriculum Development', 'fa-book-open', 'Designing educational programs'],
            ['Educational Technology', 'fa-laptop', 'Technology in teaching and learning'],
            ['Special Education', 'fa-hands-holding-child', 'Teaching students with disabilities'],
            ['Educational Psychology', 'fa-brain', 'Learning and development psychology'],
        ],
        'Psychology' => [
            ['BA Psychology', 'fa-brain', 'Bachelor of Arts in Psychology'],
            ['BSc Psychology', 'fa-brain', 'Bachelor of Science in Psychology'],
            ['Clinical Psychology', 'fa-user-doctor', 'Assessment and treatment of mental illness'],
            ['Counseling Psychology', 'fa-handshake', 'Guidance and emotional support'],
            ['Developmental Psychology', 'fa-baby', 'Human growth across the lifespan'],
            ['Organizational Psychology', 'fa-users', 'Psychology in the workplace'],
        ],
        'Architecture' => [
            ['Bachelor of Architecture (B.Arch)', 'fa-building-columns', 'Professional architecture degree'],
            ['Interior Design', 'fa-couch', 'Interior space planning and design'],
            ['Urban Planning', 'fa-city', 'City and regional planning'],
            ['Landscape Architecture', 'fa-tree-city', 'Design of outdoor spaces and landscapes'],
            ['Architectural Engineering', 'fa-building', 'Engineering of buildings and structures'],
            ['Sustainable Architecture', 'fa-leaf', 'Eco-friendly and green building design'],
        ],
        'Arts & Design' => [
            ['Bachelor of Fine Arts (BFA)', 'fa-palette', 'Professional degree in visual arts'],
            ['Graphic Design', 'fa-pen-nib', 'Visual communication and design'],
            ['Fashion Design', 'fa-shirt', 'Clothing and fashion creation'],
            ['Animation', 'fa-clapperboard', '2D/3D animation and visual effects'],
            ['Photography', 'fa-camera', 'Professional photography and editing'],
            ['Product Design', 'fa-cube', 'Industrial and product design'],
            ['Visual Communication', 'fa-eye', 'Visual media and communication design'],
        ],
        'Media & Communication' => [
            ['BA Journalism', 'fa-newspaper', 'Bachelor of Arts in Journalism'],
            ['Mass Communication', 'fa-tower-broadcast', 'Broadcasting and mass media'],
            ['Public Relations', 'fa-users', 'Reputation and public communication'],
            ['Film Studies', 'fa-film', 'Cinema theory and filmmaking'],
            ['Digital Media', 'fa-mobile-screen', 'Online content and media production'],
            ['Advertising and PR', 'fa-bullhorn', 'Advertising and public relations'],
        ],
        'Hospitality & Tourism' => [
            ['BHM (Hotel Management)', 'fa-hotel', 'Bachelor of Hotel Management'],
            ['Tourism Management', 'fa-plane-departure', 'Travel and tourism operations'],
            ['Culinary Arts', 'fa-utensils', 'Professional cooking and kitchen management'],
            ['Event Management', 'fa-calendar-check', 'Planning and organizing events'],
            ['Travel and Tourism', 'fa-map-location-dot', 'Travel services and tour operation'],
            ['Hospitality Administration', 'fa-hotel', 'Management of hospitality businesses'],
        ],
    ],

    // ============ ~400 SUBJECTS (2 per course) ============
    'subjects' => [
        // Information Technology
        'BCA' => ['Computer Fundamentals', 'Programming in C', 'Digital Logic', 'Mathematics', 'Data Structures and Algorithms', 'Database Management System', 'Web Technology', 'Object-Oriented Programming', 'Java Programming', 'Operating Systems', 'Software Engineering', 'Computer Networks', 'System Analysis and Design', 'Statistics', 'Artificial Intelligence', 'Project Work'],
        'BSc CSIT' => ['Discrete Structure', 'Computer Architecture', 'Data Structures', 'Operating Systems', 'Database Systems', 'Machine Learning', 'Web Technology'],
        'BIT' => ['Programming', 'Database', 'Web Development', 'Networking', 'Data Analytics', 'Cloud Computing'],
        'B.Tech Computer Engineering' => ['Digital Electronics', 'Microprocessors', 'Computer Networks', 'Database Systems'],
        'Software Engineering' => ['Software Requirements', 'System Design', 'Software Testing', 'Agile & DevOps', 'Web Development'],
        'Computer Science' => ['Algorithms', 'Theory of Computation', 'Compilers', 'Data Structures'],
        'Information Technology' => ['IT Fundamentals', 'Database Systems', 'Networking', 'Web Development'],
        'Data Science' => ['Statistics', 'Machine Learning', 'Data Visualization', 'Python Programming', 'Big Data Analytics'],
        // Computer Engineering
        'BE Computer Engineering' => ['Digital Logic', 'Computer Architecture', 'Microprocessors', 'Computer Networks'],
        'Computer Engineering' => ['Digital Logic', 'Computer Architecture', 'Microcontrollers', 'Data Structures'],
        'Embedded Systems' => ['Embedded C', 'RTOS', 'IoT', 'Firmware Development'],
        'Computer Hardware and Networking' => ['Computer Hardware', 'Network Administration', 'Cisco Networking', 'System Administration'],
        'VLSI Design' => ['VLSI Design', 'CMOS Circuits', 'FPGA', 'Hardware Description Language'],
        'Robotics Engineering' => ['Robotics', 'Control Systems', 'Sensors & Actuators', 'Robot Programming'],
        'IoT Engineering' => ['IoT Architecture', 'Sensor Networks', 'Embedded Systems', 'Wireless Communication'],
        // Civil Engineering
        'BE Civil Engineering' => ['Surveying', 'Structural Analysis', 'Concrete Technology', 'Fluid Mechanics'],
        'Civil Engineering' => ['Engineering Drawing', 'Building Construction', 'Soil Mechanics'],
        'Structural Engineering' => ['Steel Design', 'Reinforced Concrete', 'Earthquake Engineering', 'Finite Element Analysis'],
        'Transportation Engineering' => ['Highway Engineering', 'Traffic Engineering', 'Transportation Planning'],
        'Geotechnical Engineering' => ['Foundation Engineering', 'Geotechnical Investigation'],
        'Water Resources Engineering' => ['Hydrology', 'Hydraulics', 'Irrigation Engineering', 'Watershed Management'],
        'Construction Management' => ['Construction Planning', 'Project Scheduling', 'Construction Safety', 'Cost Estimation'],
        // Mechanical Engineering
        'BE Mechanical Engineering' => ['Engineering Mechanics', 'Thermodynamics', 'Machine Design', 'Manufacturing Processes'],
        'Mechanical Engineering' => ['Thermodynamics', 'Fluid Mechanics', 'Machine Design', 'Strength of Materials'],
        'Automobile Engineering' => ['Internal Combustion Engines', 'Vehicle Dynamics', 'Automotive Electronics', 'Electric Vehicles'],
        'Thermal Engineering' => ['Heat Transfer', 'Refrigeration', 'Thermodynamics', 'Energy Systems'],
        'Manufacturing Engineering' => ['CNC Machining', 'Production Planning', 'Welding Technology', 'Quality Control'],
        'Mechatronics' => ['Control Systems', 'Embedded Systems', 'Sensors & Actuators', 'Robotics'],
        'Aerospace Engineering' => ['Aerodynamics', 'Propulsion', 'Aircraft Structures', 'Flight Mechanics'],
        'Robotics and Automation' => ['Industrial Robotics', 'PLC Programming', 'Automation Systems', 'Robot Vision'],
        // Electrical Engineering
        'BE Electrical Engineering' => ['Circuit Theory', 'Electrical Machines', 'Power Systems', 'Control Systems'],
        'Electrical Engineering' => ['Circuit Analysis', 'Electrical Machines', 'Power Electronics', 'Electric Circuits'],
        'Power Systems Engineering' => ['Power Generation', 'Transmission Lines', 'Power Distribution', 'Smart Grid'],
        'Control Systems' => ['Control Theory', 'PID Controllers', 'System Dynamics', 'Automation'],
        'Renewable Energy' => ['Solar Energy', 'Wind Energy', 'Energy Storage', 'Grid Integration'],
        'Instrumentation Engineering' => ['Instrumentation', 'Process Control', 'Sensors & Transducers', 'Mechatronics'],
        'Microelectronics' => ['Semiconductor Devices', 'IC Design', 'Microfabrication', 'Analog Circuits'],
        // Electronics Engineering
        'BE Electronics Engineering' => ['Electronic Devices', 'Analog Circuits', 'Digital Electronics', 'Communication Systems'],
        'Electronics and Communication' => ['Signals & Systems', 'Digital Communication', 'Microwave Engineering', 'Embedded Systems'],
        'VLSI and Embedded Systems' => ['VLSI Design', 'Embedded Programming', 'FPGA', 'SoC Design'],
        'Consumer Electronics' => ['Audio Systems', 'Display Technology', 'Consumer Devices', 'Smart Appliances'],
        'Signal Processing' => ['Digital Signal Processing', 'Image Processing', 'Speech Processing', 'Filter Design'],
        'Biomedical Electronics' => ['Medical Instrumentation', 'Biomedical Sensors', 'Biosignals', 'Medical Imaging'],
        'Power Electronics' => ['Power Converters', 'Inverters', 'Motor Drives', 'Switching Devices'],
        // Chemical Engineering
        'BE Chemical Engineering' => ['Chemical Thermodynamics', 'Mass Transfer', 'Heat Transfer', 'Reaction Engineering'],
        'Chemical Engineering' => ['Chemical Processes', 'Fluid Mechanics', 'Chemical Thermodynamics', 'Process Control'],
        'Petrochemical Engineering' => ['Petroleum Refining', 'Oil & Gas Processing', 'Petrochemicals', 'Pipeline Engineering'],
        'Polymer Engineering' => ['Polymer Science', 'Polymer Processing', 'Composite Materials', 'Polymer Properties'],
        'Food Technology' => ['Food Processing', 'Food Preservation', 'Food Microbiology', 'Food Quality'],
        'Pharmaceutical Engineering' => ['Pharmaceutical Processes', 'Drug Formulation', 'Bioprocessing', 'GMP'],
        // Aerospace Engineering
        'BE Aerospace Engineering' => ['Aerodynamics', 'Aircraft Structures', 'Propulsion Systems', 'Flight Dynamics'],
        'Aerospace Engineering' => ['Aerodynamics', 'Aircraft Design', 'Propulsion', 'Space Systems'],
        'Avionics' => ['Avionics Systems', 'Flight Instruments', 'Radar Systems', 'Navigation Systems'],
        'Aeronautical Engineering' => ['Aircraft Maintenance', 'Aerodynamics', 'Flight Mechanics', 'Airframe Systems'],
        'Space Technology' => ['Satellite Systems', 'Launch Vehicles', 'Spacecraft Design', 'Orbital Mechanics'],
        'Propulsion Systems' => ['Jet Propulsion', 'Rocket Propulsion', 'Combustion', 'Turbomachinery'],
        // Medicine & Health Sciences
        'MBBS (Doctor of Medicine)' => ['Anatomy', 'Physiology', 'Biochemistry', 'Pathology', 'Pharmacology', 'Medicine', 'Surgery'],
        'BDS (Dental Surgery)' => ['Dental Anatomy', 'Oral Pathology', 'Periodontology', 'Endodontics'],
        'BHMS (Homeopathy)' => ['Homeopathic Philosophy', 'Materia Medica', 'Repertory', 'Organon of Medicine'],
        'BAMS (Ayurveda)' => ['Ayurvedic Principles', 'Dravyaguna', 'Rasa Shastra', 'Panchakarma'],
        'Physiotherapy' => ['Anatomy', 'Physiotherapy Techniques', 'Rehabilitation', 'Sports Physiotherapy'],
        'Public Health' => ['Epidemiology', 'Biostatistics', 'Health Policy', 'Community Health'],
        'Radiology' => ['Radiographic Imaging', 'CT & MRI', 'Ultrasound', 'Radiation Safety'],
        'Biomedical Science' => ['Cell Biology', 'Molecular Biology', 'Human Physiology', 'Medical Genetics'],
        // Dentistry
        'BDS (Dental Surgery)' => ['Dental Anatomy', 'Oral Pathology', 'Periodontology', 'Endodontics'],
        'Orthodontics' => ['Orthodontic Techniques', 'Tooth Movement', 'Braces', 'Cephalometrics'],
        'Periodontics' => ['Gum Disease', 'Periodontal Therapy', 'Oral Hygiene', 'Implantology'],
        'Prosthodontics' => ['Dental Prosthetics', 'Crowns & Bridges', 'Dental Implants', 'Removable Dentures'],
        'Oral Surgery' => ['Oral Anatomy', 'Extraction Techniques', 'Jaw Surgery', 'Maxillofacial Trauma'],
        // Pharmacy
        'B.Pharm' => ['Pharmaceutical Chemistry', 'Pharmacology', 'Pharmaceutics', 'Pharmacognosy'],
        'Pharm.D' => ['Clinical Pharmacy', 'Pharmacotherapeutics', 'Clinical Research', 'Drug Interactions'],
        'Pharmacology' => ['Drug Action', 'Pharmacodynamics', 'Pharmacokinetics', 'Toxicology'],
        'Clinical Pharmacy' => ['Patient Counseling', 'Therapeutic Monitoring', 'Clinical Trials', 'Drug Information'],
        'Pharmaceutical Chemistry' => ['Drug Design', 'Medicinal Chemistry', 'Organic Synthesis', 'SAR'],
        'Pharmacognosy' => ['Herbal Medicine', 'Plant Drugs', 'Essential Oils', 'Phytochemistry'],
        // Nursing
        'BSc Nursing' => ['Fundamentals of Nursing', 'Medical Surgical Nursing', 'Pediatric Nursing', 'Community Health Nursing'],
        'General Nursing and Midwifery (GNM)' => ['Anatomy & Physiology', 'Nursing Fundamentals', 'Midwifery', 'Community Nursing'],
        'Pediatric Nursing' => ['Child Health', 'Pediatric Diseases', 'Neonatal Care', 'Pediatric Emergencies'],
        'Critical Care Nursing' => ['ICU Nursing', 'Emergency Care', 'Ventilator Management', 'Critical Monitoring'],
        'Psychiatric Nursing' => ['Mental Health Nursing', 'Psychiatric Disorders', 'Psychotherapy', 'Crisis Intervention'],
        'Community Health Nursing' => ['Community Assessment', 'Home Care', 'Public Health Nursing', 'Health Education'],
        // Biotechnology
        'BSc Biotechnology' => ['Cell Biology', 'Molecular Biology', 'Genetic Engineering', 'Biochemistry'],
        'Genetic Engineering' => ['Gene Cloning', 'CRISPR', 'Transgenic Organisms', 'Genomics'],
        'Microbiology' => ['Microbial Genetics', 'Microbial Physiology', 'Clinical Microbiology', 'Industrial Microbiology'],
        'Bioinformatics' => ['Sequence Analysis', 'Genomics', 'Proteomics', 'Computational Biology'],
        'Immunology' => ['Immune System', 'Vaccines', 'Immunotherapy', 'Antibodies'],
        'Industrial Biotechnology' => ['Bioprocess Engineering', 'Fermentation', 'Enzyme Technology', 'Downstream Processing'],
        // Agriculture
        'BSc Agriculture' => ['Agronomy', 'Soil Science', 'Plant Pathology', 'Agricultural Economics', 'Horticulture'],
        'Agronomy' => ['Crop Production', 'Irrigation Management', 'Weed Science', 'Crop Rotation'],
        'Horticulture' => ['Fruit Science', 'Vegetable Science', 'Floriculture', 'Orchard Management'],
        'Plant Pathology' => ['Plant Diseases', 'Fungal Pathogens', 'Disease Control', 'Plant Virology'],
        'Soil Science' => ['Soil Chemistry', 'Soil Fertility', 'Soil Conservation', 'Soil Biology'],
        'Agricultural Economics' => ['Farm Management', 'Agribusiness', 'Agricultural Policy', 'Rural Development'],
        'Animal Husbandry' => ['Livestock Management', 'Animal Nutrition', 'Dairy Science', 'Animal Breeding'],
        // Environmental Science
        'BSc Environmental Science' => ['Ecology', 'Environmental Chemistry', 'Environmental Biology', 'Environmental Policy'],
        'Ecology' => ['Ecosystem Dynamics', 'Biodiversity', 'Conservation Biology', 'Population Ecology'],
        'Environmental Management' => ['Waste Management', 'Environmental Impact Assessment', 'Sustainability', 'Natural Resource Management'],
        'Climate Science' => ['Climatology', 'Climate Change', 'Atmospheric Science', 'Meteorology'],
        'Water Resource Management' => ['Water Conservation', 'Watershed Management', 'Hydrology', 'Water Quality'],
        'Environmental Engineering' => ['Air Pollution Control', 'Water Treatment', 'Wastewater Engineering', 'Solid Waste Management'],
        // Physics
        'BSc Physics' => ['Classical Mechanics', 'Electromagnetism', 'Quantum Mechanics', 'Thermodynamics', 'Waves & Optics'],
        'Theoretical Physics' => ['Mathematical Physics', 'Quantum Field Theory', 'Relativity', 'Statistical Mechanics'],
        'Astrophysics' => ['Stellar Physics', 'Galaxies', 'Cosmology', 'Planetary Science'],
        'Quantum Physics' => ['Quantum Mechanics', 'Quantum Computing', 'Particle Physics', 'Quantum Optics'],
        'Applied Physics' => ['Semiconductor Physics', 'Optics', 'Materials Science', 'Photonics'],
        'Nuclear Physics' => ['Nuclear Models', 'Radioactivity', 'Nuclear Reactions', 'Particle Detectors'],
        // Chemistry
        'BSc Chemistry' => ['Organic Chemistry', 'Inorganic Chemistry', 'Physical Chemistry', 'Analytical Chemistry'],
        'Organic Chemistry' => ['Reaction Mechanisms', 'Stereochemistry', 'Organic Synthesis', 'Spectroscopy'],
        'Inorganic Chemistry' => ['Coordination Chemistry', 'Organometallics', 'Bioinorganic Chemistry', 'Solid State'],
        'Physical Chemistry' => ['Thermodynamics', 'Kinetics', 'Quantum Chemistry', 'Electrochemistry'],
        'Analytical Chemistry' => ['Titration', 'Chromatography', 'Spectroscopy', 'Instrumental Analysis'],
        'Biochemistry' => ['Metabolism', 'Enzymology', 'Molecular Biology', 'Bioenergetics'],
        // Mathematics
        'BSc Mathematics' => ['Calculus', 'Linear Algebra', 'Abstract Algebra', 'Real Analysis', 'Differential Equations'],
        'Pure Mathematics' => ['Number Theory', 'Abstract Algebra', 'Topology', 'Mathematical Logic'],
        'Applied Mathematics' => ['Numerical Analysis', 'Optimization', 'Mathematical Modeling', 'Differential Equations'],
        'Computational Mathematics' => ['Numerical Methods', 'Scientific Computing', 'Simulation', 'Algorithms'],
        'Mathematical Statistics' => ['Probability', 'Statistical Inference', 'Bayesian Statistics', 'Stochastic Processes'],
        'Actuarial Science' => ['Actuarial Mathematics', 'Risk Management', 'Financial Mathematics', 'Life Insurance'],
        // Statistics
        'BSc Statistics' => ['Probability', 'Statistical Inference', 'Regression Analysis', 'Sampling Theory'],
        'Data Analytics' => ['Data Mining', 'Data Visualization', 'Predictive Analytics', 'Big Data'],
        'Biostatistics' => ['Clinical Trials', 'Epidemiological Methods', 'Survival Analysis', 'Bioinformatics Statistics'],
        'Econometrics' => ['Regression Models', 'Time Series', 'Panel Data', 'Econometric Theory'],
        'Statistical Computing' => ['R Programming', 'Python for Statistics', 'Machine Learning', 'Statistical Software'],
        // Business Administration
        'BBA' => ['Principles of Management', 'Marketing Management', 'Financial Management', 'Organizational Behavior', 'Business Communication'],
        'MBA' => ['Strategic Management', 'Corporate Finance', 'Operations Management', 'Leadership', 'Business Strategy'],
        'Human Resource Management' => ['Recruitment & Selection', 'Training & Development', 'Compensation', 'Labor Relations'],
        'Operations Management' => ['Supply Chain Management', 'Production Planning', 'Quality Management', 'Inventory Control'],
        'Entrepreneurship' => ['Business Planning', 'Startup Funding', 'Innovation Management', 'Small Business Management'],
        'International Business' => ['Global Marketing', 'International Trade', 'Cross-Cultural Management', 'Foreign Market Entry'],
        'Business Analytics' => ['Data Analysis', 'Business Intelligence', 'Predictive Modeling', 'Decision Analytics'],
        'Project Management' => ['Project Planning', 'Risk Management', 'Agile Project Management', 'Budgeting'],
        // Finance & Accounting
        'BCom (Commerce)' => ['Financial Accounting', 'Business Economics', 'Corporate Law', 'Statistics'],
        'CA (Chartered Accountancy)' => ['Financial Accounting', 'Auditing', 'Taxation', 'Corporate Finance'],
        'Finance' => ['Corporate Finance', 'Investment Analysis', 'Financial Markets', 'Portfolio Management'],
        'Accounting' => ['Financial Accounting', 'Management Accounting', 'Cost Accounting', 'Advanced Accounting'],
        'Investment Banking' => ['Mergers & Acquisitions', 'Valuation', 'Capital Markets', 'Financial Modeling'],
        'Taxation' => ['Income Tax', 'Corporate Tax', 'Tax Planning', 'International Taxation'],
        'Auditing' => ['Audit Planning', 'Internal Audit', 'Forensic Audit', 'Audit Standards'],
        // Marketing
        'BBA Marketing' => ['Consumer Behavior', 'Marketing Research', 'Brand Management', 'Digital Marketing'],
        'Digital Marketing' => ['SEO', 'Social Media Marketing', 'Content Marketing', 'Google Ads', 'Email Marketing'],
        'Brand Management' => ['Brand Strategy', 'Brand Equity', 'Brand Positioning', 'Brand Communication'],
        'Market Research' => ['Survey Design', 'Data Analysis', 'Consumer Insights', 'Focus Groups'],
        'Advertising' => ['Creative Strategy', 'Media Planning', 'Copywriting', 'Campaign Management'],
        'Sales Management' => ['Sales Strategy', 'Territory Management', 'Key Account Management', 'Sales Forecasting'],
        // Economics
        'BA Economics' => ['Microeconomics', 'Macroeconomics', 'Econometrics', 'Development Economics'],
        'MA Economics' => ['Advanced Microeconomics', 'Advanced Macroeconomics', 'Econometrics', 'Economic Policy'],
        'Development Economics' => ['Poverty & Inequality', 'Economic Growth', 'Trade & Development', 'Policy Analysis'],
        'Microeconomics' => ['Consumer Theory', 'Producer Theory', 'Market Structures', 'Game Theory'],
        'Macroeconomics' => ['National Income', 'Monetary Policy', 'Fiscal Policy', 'Inflation & Unemployment'],
        'International Economics' => ['International Trade', 'Exchange Rates', 'Trade Policy', 'Global Finance'],
        // Law
        'LLB' => ['Constitutional Law', 'Criminal Law', 'Contract Law', 'Tort Law', 'Legal Method'],
        'LLM' => ['Advanced Legal Theory', 'Legal Research', 'Comparative Law', 'Human Rights Law'],
        'Criminal Law' => ['Criminal Procedure', 'Evidence Law', 'Criminal Justice', 'Cyber Crime'],
        'Corporate Law' => ['Company Law', 'Securities Law', 'Mergers & Acquisitions', 'Corporate Governance'],
        'Constitutional Law' => ['Fundamental Rights', 'Judicial Review', 'Constitutional Amendments', 'Federalism'],
        'International Law' => ['Public International Law', 'Treaty Law', 'International Human Rights', 'International Criminal Law'],
        // Education
        'BEd' => ['Educational Psychology', 'Teaching Methods', 'Curriculum Development', 'Educational Technology'],
        'BEd in Primary Education' => ['Child Development', 'Language Teaching', 'Mathematics Teaching', 'Classroom Management'],
        'MEd' => ['Educational Leadership', 'Research Methods in Education', 'Education Policy', 'Assessment & Evaluation'],
        'Curriculum Development' => ['Curriculum Design', 'Instructional Design', 'Learning Objectives', 'Material Development'],
        'Educational Technology' => ['E-Learning', 'Multimedia in Education', 'Learning Management Systems', 'Digital Tools'],
        'Special Education' => ['Inclusive Education', 'Learning Disabilities', 'Behavioral Interventions', 'Assistive Technology'],
        'Educational Psychology' => ['Learning Theories', 'Motivation', 'Cognitive Development', 'Student Assessment'],
        // Psychology
        'BA Psychology' => ['Introduction to Psychology', 'Social Psychology', 'Abnormal Psychology', 'Research Methods'],
        'BSc Psychology' => ['Cognitive Psychology', 'Biopsychology', 'Statistics in Psychology', 'Psychometrics'],
        'Clinical Psychology' => ['Psychopathology', 'Psychological Assessment', 'Psychotherapy', 'Clinical Interventions'],
        'Counseling Psychology' => ['Counseling Theories', 'Group Counseling', 'Career Counseling', 'Crisis Counseling'],
        'Developmental Psychology' => ['Infant Development', 'Adolescence', 'Adult Development', 'Aging'],
        'Organizational Psychology' => ['Employee Motivation', 'Leadership', 'Workplace Wellbeing', 'Job Analysis'],
        // Architecture
        'Bachelor of Architecture (B.Arch)' => ['Architectural Design', 'Building Materials', 'Architectural Drawing', 'History of Architecture', 'Structural Systems'],
        'Interior Design' => ['Interior Materials', 'Space Planning', 'Furniture Design', 'Lighting Design'],
        'Urban Planning' => ['Urban Design', 'Zoning', 'Transportation Planning', 'Urban Policy'],
        'Landscape Architecture' => ['Landscape Design', 'Plant Materials', 'Site Planning', 'Environmental Design'],
        'Architectural Engineering' => ['Building Structures', 'Building Services', 'Construction Technology', 'Environmental Systems'],
        'Sustainable Architecture' => ['Green Building', 'Passive Design', 'Energy Efficiency', 'Sustainable Materials'],
        // Arts & Design
        'Bachelor of Fine Arts (BFA)' => ['Drawing', 'Painting', 'Sculpture', 'Art History', 'Printmaking'],
        'Graphic Design' => ['Typography', 'Layout Design', 'Brand Identity', 'Adobe Creative Suite'],
        'Fashion Design' => ['Fashion Illustration', 'Pattern Making', 'Textile Design', 'Garment Construction'],
        'Animation' => ['2D Animation', '3D Modeling', 'Character Design', 'Visual Effects'],
        'Photography' => ['Digital Photography', 'Lighting', 'Photo Editing', 'Composition'],
        'Product Design' => ['Industrial Design', 'Product Sketching', 'CAD Modeling', 'User Experience'],
        'Visual Communication' => ['Visual Design', 'Illustration', 'Motion Graphics', 'Design Theory'],
        // Media & Communication
        'BA Journalism' => ['Reporting', 'Editing', 'News Writing', 'Media Ethics'],
        'Mass Communication' => ['Media Studies', 'Broadcasting', 'Mass Media', 'Communication Theory'],
        'Public Relations' => ['PR Strategy', 'Crisis Communication', 'Media Relations', 'Corporate Communication'],
        'Film Studies' => ['Film History', 'Screenwriting', 'Film Production', 'Directing'],
        'Digital Media' => ['Content Creation', 'Social Media', 'Digital Storytelling', 'Video Production'],
        'Advertising and PR' => ['Advertising Strategy', 'PR Campaigns', 'Brand Communication', 'Media Planning'],
        // Hospitality & Tourism
        'BHM (Hotel Management)' => ['Front Office Operations', 'Food & Beverage', 'Housekeeping', 'Hotel Accounting'],
        'Tourism Management' => ['Tourism Marketing', 'Destination Management', 'Tour Operations', 'Travel Agency Management'],
        'Culinary Arts' => ['Culinary Fundamentals', 'Baking & Pastry', 'Kitchen Management', 'Food Safety'],
        'Event Management' => ['Event Planning', 'Event Marketing', 'Logistics', 'Event Production'],
        'Travel and Tourism' => ['Travel Geography', 'Tourism Economics', 'Reservation Systems', 'Tour Guiding'],
        'Hospitality Administration' => ['Hospitality Law', 'Revenue Management', 'Facility Management', 'Guest Relations'],
    ],
];
